name: Lint the Fortran code and the MEX gateways

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 17 * * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Lint the Fortran code and the MEX gateways
    runs-on: [self-hosted, linter]
    strategy:
      fail-fast: false
      matrix:
        linter: [flint, mlint]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        run: |
          source ~/.bashrc
          export PATH=$PATH:"~/local/bin"
          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./${{ matrix.linter }} --all
