name: Test ifort

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 18 1-31/2 * *'
  # Trigger the workflow manually
  workflow_dispatch:


jobs:

  test:
    name: Run ifort tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Windows does not work. On Windows, the options for ifort/ifx starts with "/" instead of "-".
        os: [ubuntu-latest, macos-latest]
        ikind: [i2, i8]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        fflags: [-O1, -O2, -O3, -g, -fast]
        testdim: [small, big]
        exclude:
          - os: macos-latest
            ikind: i8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          submodules: recursive

      - name: Install Intel oneAPI on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: bash .github/scripts/install_oneapi_linux.sh

      - name: Install Intel oneAPI on macOS
        if: startsWith(matrix.os, 'macos')
        run: bash .github/scripts/install_oneapi_macos.sh

      - name: Miscellaneous setup
        shell: bash
        run: bash .github/scripts/misc_setup

      - name: Conduct the test
        shell: bash
        run: |
          cd "$ROOT_DIR"/fortran/${{ matrix.solver }} && bash ./flint --all && bash ./mlint --all
          cd "$ROOT_DIR"/fortran/tests
          $SEDI 's|800|100|g' test_*.f90
          if [[ -f "test_uobyqa.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 90|g' test_uobyqa.f90
          fi
          if [[ -f "test_cobyla.f90" ]] ; then
              $SEDI 's|bign = 120|bign = 80|g' test_cobyla.f90
          fi
          if [[ -f "test_bobyqa.f90" ]] ; then
              $SEDI 's|bign = 400|bign = 380|g' test_bobyqa.f90
          fi
          export FFLAGS=${{ matrix.fflags }} && export TESTDIM=${{ matrix.testdim }} && make itest_${{ matrix.ikind }}.${{ matrix.solver }}
          cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }} && make itest

      - name: Store artifacts
        uses: actions/upload-artifact@v3.1.2
        if: always()  # Always run even if the workflow is canceled manually or due to overtime.
        with:
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        run: rm -rf ${{ env.TEST_DIR }}
